
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_healthcare'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_healthcare'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_healthcare:
    # Config indicated by + and applies to all files under models/example/

vars:
  bronze_copy_config:

    database: HEALTHCARE_DB
    schema: BRONZE
    stage_name: HEALTHCARE_S3_STAGE
    format_name: HEALTHCARE_STAGE_CSV_FORMAT

    tables:
    - table_name: FY_2024_SNF_VBP_Aggregate_Performance
      pattern: '.*_FY_2024_SNF_VBP_Aggregate_Performance.*?\.csv'
      reset: true
    - table_name: FY_2024_SNF_VBP_Facility_Performance
      pattern: '.*_FY_2024_SNF_VBP_Facility_Performance.*?\.csv'
      reset: true
    - table_name: NH_Citation_Descriptions
      pattern: '.*_NH_CitationDescriptions.*?\.csv'
      reset: true
    - table_name: NH_Covid_Vax_Averages
      pattern: '.*_NH_CovidVaxAverages.*?\.csv'
      reset: true
    - table_name: NH_Covid_Vax_Provider
      pattern: '.*_NH_CovidVaxProvider.*?\.csv'
      reset: true
    - table_name: NH_Data_Collection_Intervals
      pattern: '.*_NH_DataCollectionIntervals.*?\.csv'
      reset: true
    - table_name: NH_Fire_Safety_Citations
      pattern: '.*_NH_FireSafetyCitations.*?\.csv'
      reset: true
    - table_name: NH_Health_Citations
      pattern: '.*_NH_HealthCitations.*?\.csv'
      reset: true
    - table_name: NH_Health_Inspec_Cutpoints_State
      pattern: '.*_NH_HlthInspecCutpointsState.*?\.csv'
      reset: true
    - table_name: NH_Ownership
      pattern: '.*_NH_Ownership.*?\.csv'
      reset: true
    - table_name: NH_Penalties
      pattern: '.*_NH_Penalties.*?\.csv'
      reset: true
    - table_name: NH_Provider_Info
      pattern: '.*_NH_ProviderInfo.*?\.csv'
      reset: true
    - table_name: NH_Quality_Msr_Claims
      pattern: '.*_NH_QualityMsr_Claims.*?\.csv'
      reset: true
    - table_name: NH_Quality_Msr_MDS
      pattern: '.*_NH_QualityMsr_MDS.*?\.csv'
      reset: true
    - table_name: NH_State_US_Averages
      pattern: '.*_NH_StateUSAverages.*?\.csv'
      reset: true
    - table_name: NH_Survey_Dates
      pattern: '.*_NH_SurveyDates.*?\.csv'
      reset: true
    - table_name: NH_Survey_Summary
      pattern: '.*_NH_SurveySummary.*?\.csv'
      reset: true
    - table_name: PBJ_Daily_Nurse_Staffing_Main
      pattern: '.*_PBJ_Daily_Nurse_Staffing.*?\.csv'
      reset: true
    - table_name: Skilled_Nursing_Facility_Quality_Reporting_Program_National_Data
      pattern: '.*_Skilled_Nursing_Facility_Quality_Reporting_Program_National_Data.*?\.csv'
      reset: true
    - table_name: Skilled_Nursing_Facility_Quality_Reporting_Program_Provider_Data
      pattern: '.*_Skilled_Nursing_Facility_Quality_Reporting_Program_Provider_Data.*?\.csv'
      reset: true
    - table_name: Swing_Bed_SNF_data
      pattern: '.*_Swing_Bed_SNF_data.*?\.csv'
      reset: true
