{{ 
    config(
        database='HEALTHCARE_DB',
        schema='SILVER',
        materialized='table',
        tags=['silver', 'healthcare']
    )
}}

-- First, grab all the data from our source
WITH source_data AS (
    SELECT
        *
    FROM
         {{ source('bronze', 'nh_provider_info') }}
),
-- Next, try to remove duplicates.  This is achieved by selecting the fields
-- we want to retain, applying a TRIM() function to them to remove leading/traling
-- spacces, then applying a "row_number()" aggregator function to apply a 
-- numeric row number to each unique row.  Duplicate rows will have a row number
-- greater than 1, so we can filter those out in the next CTE.
deduplicated AS (
    SELECT
        TRIM(CMS_CERTIFICATION_NUMBER) AS provider_id,
        TRIM(PROVIDER_NAME) AS provider_name,
        TRIM(PROVIDER_ADDRESS) AS provider_address,
        TRIM(CITY_TOWN) AS city_town,
        TRIM(STATE) AS state,
        TRIM(ZIP_CODE) AS zip_code,
        TRIM(TELEPHONE_NUMBER) AS telephone_number,
        TRIM(PROVIDER_SSA_COUNTY_CODE) AS provider_ssa_county_code,
        TRIM(COUNTY_PARISH) AS county_parish,
        TRIM(OWNERSHIP_TYPE) AS ownership_type,
        TRIM(NUMBER_OF_CERTIFIED_BEDS) AS number_of_certified_beds,
        TRIM(AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY) AS average_number_of_residents_per_day,
        TRIM(AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY_FOOTNOTE) AS average_number_of_residents_per_day_footnote,
        TRIM(PROVIDER_TYPE) AS provider_type,
        TRIM(PROVIDER_RESIDES_IN_HOSPITAL) AS provider_resides_in_hospital,
        TRIM(LEGAL_BUSINESS_NAME) AS legal_business_name,
        TRIM(DATE_FIRST_APPROVED_TO_PROVIDE_MEDICARE_AND_MEDICAID_SERVICES) AS date_first_approved_to_provide_medicare_and_medicaid_services,
        TRIM(AFFILIATED_ENTITY_NAME) AS affiliated_entity_name,
        TRIM(AFFILIATED_ENTITY_ID) AS affiliated_entity_id,
        TRIM(CONTINUING_CARE_RETIREMENT_COMMUNITY) AS continuing_care_retirement_community,
        TRIM(SPECIAL_FOCUS_STATUS) AS special_focus_status,
        TRIM(ABUSE_ICON) AS abuse_icon,
        TRIM(MOST_RECENT_HEALTH_INSPECTION_MORE_THAN_2_YEARS_AGO) AS most_recent_health_inspection_more_than_2_years_ago,
        TRIM(PROVIDER_CHANGED_OWNERSHIP_IN_LAST_12_MONTHS) AS provider_changed_ownership_in_last_12_months,
        TRIM(WITH_A_RESIDENT_AND_FAMILY_COUNCIL) AS with_a_resident_and_family_council,
        TRIM(AUTOMATIC_SPRINKLER_SYSTEMS_IN_ALL_REQUIRED_AREAS) AS automatic_sprinkler_systems_in_all_required_areas,
        TRIM(OVERALL_RATING) AS overall_rating,
        TRIM(OVERALL_RATING_FOOTNOTE) AS overall_rating_footnote,
        TRIM(HEALTH_INSPECTION_RATING) AS health_inspection_rating,
        TRIM(HEALTH_INSPECTION_RATING_FOOTNOTE) AS health_inspection_rating_footnote,
        TRIM(QM_RATING) AS qm_rating,
        TRIM(QM_RATING_FOOTNOTE) AS qm_rating_footnote,
        TRIM(LONG_STAY_QM_RATING) AS long_stay_qm_rating,
        TRIM(LONG_STAY_QM_RATING_FOOTNOTE) AS long_stay_qm_rating_footnote,
        TRIM(SHORT_STAY_QM_RATING) AS short_stay_qm_rating,
        TRIM(SHORT_STAY_QM_RATING_FOOTNOTE) AS short_stay_qm_rating_footnote,
        TRIM(STAFFING_RATING) AS staffing_rating,
        TRIM(STAFFING_RATING_FOOTNOTE) AS staffing_rating_footnote,
        TRIM(REPORTED_STAFFING_FOOTNOTE) AS reported_staffing_footnote,
        TRIM(PHYSICAL_THERAPIST_STAFFING_FOOTNOTE) AS physical_therapist_staffing_footnote,
        TRIM(REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS reported_nurse_aide_staffing_hours_per_resident_per_day,
        TRIM(REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS reported_lpn_staffing_hours_per_resident_per_day,
        TRIM(REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS reported_rn_staffing_hours_per_resident_per_day,
        TRIM(REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS reported_licensed_staffing_hours_per_resident_per_day,
        TRIM(REPORTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS reported_total_nurse_staffing_hours_per_resident_per_day,
        TRIM(TOTAL_NUMBER_OF_NURSE_STAFF_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND) AS total_number_of_nurse_staff_hours_per_resident_per_day_on_the_weekend,
        TRIM(REGISTERED_NURSE_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND) AS registered_nurse_hours_per_resident_per_day_on_the_weekend,
        TRIM(REPORTED_PHYSICAL_THERAPIST_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS reported_physical_therapist_staffing_hours_per_resident_per_day,
        TRIM(TOTAL_NURSING_STAFF_TURNOVER) AS total_nursing_staff_turnover,
        TRIM(TOTAL_NURSING_STAFF_TURNOVER_FOOTNOTE) AS total_nursing_staff_turnover_footnote,
        TRIM(REGISTERED_NURSE_TURNOVER) AS registered_nurse_turnover,
        TRIM(REGISTERED_NURSE_TURNOVER_FOOTNOTE) AS registered_nurse_turnover_footnote,
        TRIM(NUMBER_OF_ADMINISTRATORS_WHO_HAVE_LEFT_THE_NURSING_HOME) AS number_of_administrators_who_have_left_the_nursing_home,
        TRIM(ADMINISTRATOR_TURNOVER_FOOTNOTE) AS administrator_turnover_footnote,
        TRIM(NURSING_CASE_MIX_INDEX) AS nursing_case_mix_index,
        TRIM(NURSING_CASE_MIX_INDEX_RATIO) AS nursing_case_mix_index_ratio,
        TRIM(CASE_MIX_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS case_mix_nurse_aide_staffing_hours_per_resident_per_day,
        TRIM(CASE_MIX_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS case_mix_lpn_staffing_hours_per_resident_per_day,
        TRIM(CASE_MIX_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS case_mix_rn_staffing_hours_per_resident_per_day,
        TRIM(CASE_MIX_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS case_mix_total_nurse_staffing_hours_per_resident_per_day,
        TRIM(CASE_MIX_WEEKEND_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS case_mix_weekend_total_nurse_staffing_hours_per_resident_per_day,
        TRIM(ADJUSTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS adjusted_nurse_aide_staffing_hours_per_resident_per_day,
        TRIM(ADJUSTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS adjusted_lpn_staffing_hours_per_resident_per_day,
        TRIM(ADJUSTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS adjusted_rn_staffing_hours_per_resident_per_day,
        TRIM(ADJUSTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS adjusted_total_nurse_staffing_hours_per_resident_per_day,
        TRIM(ADJUSTED_WEEKEND_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) AS adjusted_weekend_total_nurse_staffing_hours_per_resident_per_day,
        TRIM(RATING_CYCLE_1_STANDARD_SURVEY_HEALTH_DATE) AS rating_cycle_1_standard_survey_health_date,
        TRIM(RATING_CYCLE_1_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES) AS rating_cycle_1_total_number_of_health_deficiencies,
        TRIM(RATING_CYCLE_1_NUMBER_OF_STANDARD_HEALTH_DEFICIENCIES) AS rating_cycle_1_number_of_standard_health_deficiencies,
        TRIM(RATING_CYCLE_1_NUMBER_OF_COMPLAINT_HEALTH_DEFICIENCIES) AS rating_cycle_1_number_of_complaint_health_deficiencies,
        TRIM(RATING_CYCLE_1_HEALTH_DEFICIENCY_SCORE) AS rating_cycle_1_health_deficiency_score,
        TRIM(RATING_CYCLE_1_NUMBER_OF_HEALTH_REVISITS) AS rating_cycle_1_number_of_health_revisits,
        TRIM(RATING_CYCLE_1_HEALTH_REVISIT_SCORE) AS rating_cycle_1_health_revisit_score,
        TRIM(RATING_CYCLE_1_TOTAL_HEALTH_SCORE) AS rating_cycle_1_total_health_score,
        TRIM(RATING_CYCLE_2_STANDARD_HEALTH_SURVEY_DATE) AS rating_cycle_2_standard_health_survey_date,
        TRIM(RATING_CYCLE_2_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES) AS rating_cycle_2_total_number_of_health_deficiencies,
        TRIM(RATING_CYCLE_2_NUMBER_OF_STANDARD_HEALTH_DEFICIENCIES) AS rating_cycle_2_number_of_standard_health_deficiencies,
        TRIM(RATING_CYCLE_2_NUMBER_OF_COMPLAINT_HEALTH_DEFICIENCIES) AS rating_cycle_2_number_of_complaint_health_deficiencies,
        TRIM(RATING_CYCLE_2_HEALTH_DEFICIENCY_SCORE) AS rating_cycle_2_health_deficiency_score,
        TRIM(RATING_CYCLE_2_NUMBER_OF_HEALTH_REVISITS) AS rating_cycle_2_number_of_health_revisits,
        TRIM(RATING_CYCLE_2_HEALTH_REVISIT_SCORE) AS rating_cycle_2_health_revisit_score,
        TRIM(RATING_CYCLE_2_TOTAL_HEALTH_SCORE) AS rating_cycle_2_total_health_score,
        TRIM(RATING_CYCLE_3_STANDARD_HEALTH_SURVEY_DATE) AS rating_cycle_3_standard_health_survey_date,
        TRIM(RATING_CYCLE_3_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES) AS rating_cycle_3_total_number_of_health_deficiencies,
        TRIM(RATING_CYCLE_3_NUMBER_OF_STANDARD_HEALTH_DEFICIENCIES) AS rating_cycle_3_number_of_standard_health_deficiencies,
        TRIM(RATING_CYCLE_3_NUMBER_OF_COMPLAINT_HEALTH_DEFICIENCIES) AS rating_cycle_3_number_of_complaint_health_deficiencies,
        TRIM(RATING_CYCLE_3_HEALTH_DEFICIENCY_SCORE) AS rating_cycle_3_health_deficiency_score,
        TRIM(RATING_CYCLE_3_NUMBER_OF_HEALTH_REVISITS) AS rating_cycle_3_number_of_health_revisits,
        TRIM(RATING_CYCLE_3_HEALTH_REVISIT_SCORE) AS rating_cycle_3_health_revisit_score,
        TRIM(RATING_CYCLE_3_TOTAL_HEALTH_SCORE) AS rating_cycle_3_total_health_score,
        TRIM(TOTAL_WEIGHTED_HEALTH_SURVEY_SCORE) AS total_weighted_health_survey_score,
        TRIM(NUMBER_OF_FACILITY_REPORTED_INCIDENTS) AS number_of_facility_reported_incidents,
        TRIM(NUMBER_OF_SUBSTANTIATED_COMPLAINTS) AS number_of_substantiated_complaints,
        TRIM(NUMBER_OF_CITATIONS_FROM_INFECTION_CONTROL_INSPECTIONS) AS number_of_citations_from_infection_control_inspections,
        TRIM(NUMBER_OF_FINES) AS number_of_fines,
        TRIM(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS) AS total_amount_of_fines_in_dollars,
        TRIM(NUMBER_OF_PAYMENT_DENIALS) AS number_of_payment_denials,
        TRIM(TOTAL_NUMBER_OF_PENALTIES) AS total_number_of_penalties,
        TRIM(LOCATION) AS location,
        TRIM(LATITUDE) AS latitude,
        TRIM(LONGITUDE) AS longitude,
        TRIM(GEOCODING_FOOTNOTE) AS geocoding_footnote,
        TRIM(PROCESSING_DATE) AS processing_date,
        TRIM(LOAD_TIMESTAMP) AS load_timestamp,
        ROW_NUMBER() OVER(PARTITION BY provider_id ORDER BY load_timestamp DESC NULLS LAST) AS rn
    FROM
        source_data
),
final AS (
    SELECT
        provider_id,
        provider_name,
        provider_address,
        city_town,
        state,
        zip_code,
        telephone_number,
        provider_ssa_county_code,
        county_parish,
        ownership_type,
        number_of_certified_beds,
        average_number_of_residents_per_day,
        average_number_of_residents_per_day_footnote,
        provider_type,
        provider_resides_in_hospital,
        legal_business_name,
        date_first_approved_to_provide_medicare_and_medicaid_services,
        affiliated_entity_name,
        affiliated_entity_id,
        continuing_care_retirement_community,
        special_focus_status,
        abuse_icon,
        most_recent_health_inspection_more_than_2_years_ago,
        provider_changed_ownership_in_last_12_months,
        with_a_resident_and_family_council,
        automatic_sprinkler_systems_in_all_required_areas,
        overall_rating,
        overall_rating_footnote,
        health_inspection_rating,
        health_inspection_rating_footnote,
        qm_rating,
        qm_rating_footnote,
        long_stay_qm_rating,
        long_stay_qm_rating_footnote,
        short_stay_qm_rating,
        short_stay_qm_rating_footnote,
        staffing_rating,
        staffing_rating_footnote,
        reported_staffing_footnote,
        physical_therapist_staffing_footnote,
        reported_nurse_aide_staffing_hours_per_resident_per_day,
        reported_lpn_staffing_hours_per_resident_per_day,
        reported_rn_staffing_hours_per_resident_per_day,
        reported_licensed_staffing_hours_per_resident_per_day,
        reported_total_nurse_staffing_hours_per_resident_per_day,
        total_number_of_nurse_staff_hours_per_resident_per_day_on_the_weekend,
        registered_nurse_hours_per_resident_per_day_on_the_weekend,
        reported_physical_therapist_staffing_hours_per_resident_per_day,
        total_nursing_staff_turnover,
        total_nursing_staff_turnover_footnote,
        registered_nurse_turnover,
        registered_nurse_turnover_footnote,
        number_of_administrators_who_have_left_the_nursing_home,
        administrator_turnover_footnote,
        nursing_case_mix_index,
        nursing_case_mix_index_ratio,
        case_mix_nurse_aide_staffing_hours_per_resident_per_day,
        case_mix_lpn_staffing_hours_per_resident_per_day,
        case_mix_rn_staffing_hours_per_resident_per_day,
        case_mix_total_nurse_staffing_hours_per_resident_per_day,
        case_mix_weekend_total_nurse_staffing_hours_per_resident_per_day,
        adjusted_nurse_aide_staffing_hours_per_resident_per_day,
        adjusted_lpn_staffing_hours_per_resident_per_day,
        adjusted_rn_staffing_hours_per_resident_per_day,
        adjusted_total_nurse_staffing_hours_per_resident_per_day,
        adjusted_weekend_total_nurse_staffing_hours_per_resident_per_day,
        rating_cycle_1_standard_survey_health_date,
        rating_cycle_1_total_number_of_health_deficiencies,
        rating_cycle_1_number_of_standard_health_deficiencies,
        rating_cycle_1_number_of_complaint_health_deficiencies,
        rating_cycle_1_health_deficiency_score,
        rating_cycle_1_number_of_health_revisits,
        rating_cycle_1_health_revisit_score,
        rating_cycle_1_total_health_score,
        rating_cycle_2_standard_health_survey_date,
        rating_cycle_2_total_number_of_health_deficiencies,
        rating_cycle_2_number_of_standard_health_deficiencies,
        rating_cycle_2_number_of_complaint_health_deficiencies,
        rating_cycle_2_health_deficiency_score,
        rating_cycle_2_number_of_health_revisits,
        rating_cycle_2_health_revisit_score,
        rating_cycle_2_total_health_score,
        rating_cycle_3_standard_health_survey_date,
        rating_cycle_3_total_number_of_health_deficiencies,
        rating_cycle_3_number_of_standard_health_deficiencies,
        rating_cycle_3_number_of_complaint_health_deficiencies,
        rating_cycle_3_health_deficiency_score,
        rating_cycle_3_number_of_health_revisits,
        rating_cycle_3_health_revisit_score,
        rating_cycle_3_total_health_score,
        total_weighted_health_survey_score,
        number_of_facility_reported_incidents,
        number_of_substantiated_complaints,
        number_of_citations_from_infection_control_inspections,
        number_of_fines,
        total_amount_of_fines_in_dollars,
        number_of_payment_denials,
        total_number_of_penalties,
        location,
        latitude,
        longitude,
        geocoding_footnote,
        processing_date
    FROM
        deduplicated
    WHERE
        rn = 1
)
SELECT
    *
FROM
    final